### ISSUE TITLE
Proposal for component lifecycle methods

### ISSUE THREAD

**Issue by geist-2501** [Quillraven/Fleks#103]
Hi all!

I've been tinkering with Fleks and, while the component hooks are lovely and work perfectly, I wondered why there isn't lifecycle methods on components instead. 

My specific use-case is that my components can raise events in order to talk to the UI. To do this they need an event manager which I inject - however, components don't have the whole Fleks context thing so I can't inject directly. So instead, I have to initialise it via a hook (which _do_ have a Fleks context), which works great, but took me a while to think of 🗿.

Wouldn't lifecycle methods be more developer friendly? For instance;

```kotlin
class ToolbarComponent : Component<ToolbarComponent> {

    private lateinit var eventManager: EventManager
    
    override fun World.onAddComponent() {
        eventManager = inject()
    }

    // Instead of;
    
    companion object : ComponentType<ToolbarComponent>() {
        val onAddComponent: ComponentHook<ToolbarComponent> = { entity, toolbarComponent ->
            toolbarComponent.eventManager = inject()
        }
    }
}
```

I've forked this repo and got the lifecycle methods working, but I'd be interested to know peoples opinions on whether this is actually a better approach :)

Also Fleks is awesome! Very happy that I made the switch from Ashley halfway through my project.

**Comment by Quillraven** [comment]
My reason for it was that I thought you don't need these methods for every single component AND performance reasons.

What would be interesting for me is how much slower it gets when we add onAdd/onRemove as default functions to a component and call it in the specific ComponentHolder functions where the hooks are currently called.

There is a benchmark sourceSet with a manual.kt file in it. You can run it before and after your changes for a quick comparison. Run it a few times and take the average values.

This is what I usually do to test such changes. The gradle benchmarkJvm task is the real one but takes veeeery long, that's why I don't recommend it for quick testing 😉

Also, ignore the result in the comments of manual.kt file. You will most likely have different numbers. Those are the ones from my PC which was also used for the benchmark table in the README.md. 

My laptop e.g. has completely different values and you will most likely also have different ones. That's why you should compare it with your own numbers and run it before and after your changes.

**Comment by geist-2501** [comment]
Ah! I never considered that it could have a performance impact - I figured it would be the same as with the hooks.

I did a spot of research, and even though the default implementation of the lifecycle methods would just be `fun World.onAddComponent() = Unit`, the function call would still exist in the bytecode. It is up to the JVM implementation to optimise the call away, which will vary from user to user :( - and I have absolutely not a clue for Kotlin Native / Multiplatform.

Performed the benchmarks - from what I can see, there isn't much difference 🎉. I ran 3 batches of benchmarks at different times of the day, and each benchmark ran 10 times instead 3 times to smooth out variance. 

Before;

```
  ADD_REMOVE:
Artemis: max(20)    min(2)  avg(6.5) 
Artemis: max(22)    min(2)  avg(6.5)
Artemis: max(20)    min(1)  avg(6.4)  
Fleks:   max(16)    min(2)  avg(5.7) 
Fleks:   max(16)    min(3)  avg(5.9) 
Fleks:   max(16)    min(3)  avg(5.7)
  SIMPLE:
Artemis: max(26)    min(14)  avg(18.2)
Artemis: max(19)    min(15)  avg(16.3) 
Artemis: max(16)    min(13)  avg(14.2)  
Fleks:   max(18)    min(15)  avg(16.6)  
Fleks:   max(26)    min(24)  avg(25.3) 
Fleks:   max(23)    min(16)  avg(18.4) 
  COMPLEX:
Artemis: max(662)    min(588)  avg(610.0) 
Artemis: max(698)    min(585)  avg(615.4) 
Artemis: max(653)    min(574)  avg(611.4)
Fleks:   max(973)    min(784)  avg(862.3)
Fleks:   max(988)    min(761)  avg(857.9)
Fleks:   max(1043)    min(838)  avg(947.2) 
```

After;

```
  ADD_REMOVE:
Artemis: max(22)    min(1)  avg(7.2)  
Artemis: max(21)    min(2)  avg(6.9)  
Artemis: max(20)    min(1)  avg(6.4)  
Fleks:   max(16)    min(2)  avg(5.6)
Fleks:   max(15)    min(2)  avg(5.5)
Fleks:   max(15)    min(2)  avg(5.6)
  SIMPLE:
Artemis: max(25)    min(15)  avg(17.7) 
Artemis: max(19)    min(15)  avg(17.8) 
Artemis: max(20)    min(13)  avg(15.2) 
Fleks:   max(33)    min(27)  avg(29.9) 
Fleks:   max(19)    min(17)  avg(18.2) 
Fleks:   max(33)    min(27)  avg(30.4) 
  COMPLEX:
Artemis: max(639)    min(582)  avg(606.2) 
Artemis: max(681)    min(597)  avg(632.4) 
Artemis: max(685)    min(566)  avg(607.3) 
Fleks:   max(952)    min(750)  avg(860.4)  
Fleks:   max(948)    min(744)  avg(843.4)  
Fleks:   max(943)    min(751)  avg(845.3)  
```
